// This file is automatically generated by the Amplify CLI when running `amplify init`.
// The values are placeholders and should be replaced by your actual AWS resources
// after running Amplify commands.

const awsExports = {
  aws_project_region: 'YOUR_AWS_REGION',
  aws_cognito_identity_pool_id: 'YOUR_IDENTITY_POOL_ID',
  aws_cognito_region: 'YOUR_AWS_REGION',
  aws_user_pools_id: 'YOUR_USER_POOL_ID',
  aws_user_pools_web_client_id: 'YOUR_WEB_CLIENT_ID',
  aws_appsync_graphqlEndpoint: 'YOUR_GRAPHQL_ENDPOINT',
  aws_appsync_region: 'YOUR_AWS_REGION',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsExports;
